set_property IOSTANDARD LVCMOS33 [get_ports {LED_tri_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_tri_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_tri_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_tri_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_tri_o[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_tri_o[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_tri_o[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED_tri_o[7]}]

set_property PACKAGE_PIN AG14 [get_ports {LED_tri_o[0]}]
set_property PACKAGE_PIN AF13 [get_ports {LED_tri_o[1]}]
set_property PACKAGE_PIN AE13 [get_ports {LED_tri_o[2]}]
set_property PACKAGE_PIN AJ14 [get_ports {LED_tri_o[3]}]
set_property PACKAGE_PIN AJ15 [get_ports {LED_tri_o[4]}]
set_property PACKAGE_PIN AH13 [get_ports {LED_tri_o[5]}]
set_property PACKAGE_PIN AH14 [get_ports {LED_tri_o[6]}]
set_property PACKAGE_PIN AL12 [get_ports {LED_tri_o[7]}]
